"function mapDF(){"
+"	var word = this.text.match(/\w+/g);"
+"	if (word == null)"
+"		return;"
+"	var tf = [];"
+"	for(var i=0;i< word.length;i++){"
+"		if (tf[word[i]] == null){"
+"			emit(word[i],{"word" : word[i],"df" : 1});"
+"			tf[word[i]]=1;"
+"		}"
+"	}"
+"}"

"function reduceDF(key, vals){"
+"	var tot = 0;"
+"	for(var i=0;i< vals.length;i++){"
+"		tot +=vals[i].df;"
+"	}"
+"	return {"word" : key,"df" : tot};"
+"}"

"function mapTF(){"
+"	var word = this.text.match(/\w+/g);"
+"	if (word == null)"
+"		return;"
+"	for(var i=0;i< word.length;i++){"
+"		emit({\"word\":word[i],\"commentID\":this._id}, {\"count\":1});"
+"	}"
+"}"

"function reduceTF(key, vals){"
+"	var tot = 0;"
+"	for(var i=0;i< vals.length;i++){"
+"		tot +=vals[i].count;"
+""	}"
+"	return {\"word\":key.word,\"commentID\":key.commentID,\"count\":tot};"
+"}"